# Generated by Django 6.0.6 on 2026-06-23 12:57

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_id",
                    models.PositiveIntegerField(
                        help_text="ID категории из прайс-листа поставщика",
                        verbose_name="ID категории",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название категории (например: Смартфоны)",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Название свойства товара (например: "Диагональ (дюйм)")',
                        max_length=100,
                        unique=True,
                        verbose_name="Название характеристики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр",
                "verbose_name_plural": "Параметры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Уникальное название магазина (поставщика)",
                        max_length=100,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL поставщика",
                        null=True,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "state",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Включено - магазин принимает заказы, Выключено - импорт идет, но заказы не принимаются",
                        verbose_name="Статус приёма заказов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConfirmEmailToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания токена"
                    ),
                ),
                (
                    "key",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Ключ"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirm_email_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен подтверждения Email",
                "verbose_name_plural": "Токены подтверждения Email",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Город доставки", max_length=50, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Улица доставки", max_length=100, verbose_name="Улица"
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True,
                        help_text="Номер дома",
                        max_length=15,
                        verbose_name="Дом",
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        blank=True,
                        help_text="Номер корпуса",
                        max_length=15,
                        verbose_name="Корпус",
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True,
                        help_text="Номер строения",
                        max_length=15,
                        verbose_name="Строение",
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True,
                        help_text="Номер квартиры",
                        max_length=15,
                        verbose_name="Квартира",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Контактный номер телефона",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Владелец адреса доставки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("basket", "Статус корзины"),
                            ("new", "Новый"),
                            ("confirmed", "Подтвержден"),
                            ("assembled", "Собран"),
                            ("sent", "Отправлен"),
                            ("delivered", "Доставлен"),
                            ("canceled", "Отменен"),
                        ],
                        db_index=True,
                        default="basket",
                        help_text="Текущий статус заказа",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Адрес доставки (заполняется при подтверждении заказа из корзины)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop_app.contact",
                        verbose_name="Контакт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Покупатель, оформивший заказ",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ("-dt",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_id",
                    models.PositiveIntegerField(
                        help_text="Уникальный идентификатор товара из системы поставщика",
                        verbose_name="ID товара",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название товара",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Техническое название модели (например: apple/iphone/xs-max)",
                        max_length=255,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Текущая цена закупки",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "price_rrc",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Рекомендуемая розничная цена (РРЦ)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Рекомендуемая розничная цена",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Текущий остаток на складе поставщика",
                        verbose_name="Количество на складе",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Категория, к которой принадлежит товар",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop_app.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="ProductParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text='Значение характеристики (например: "6.5" или "золотистый")',
                        max_length=255,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        help_text="Наименование характеристики из справочника",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_parameters",
                        to="shop_app.parameter",
                        verbose_name="Параметр",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Товар, к которому привязана характеристика",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_parameters",
                        to="shop_app.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр товара",
                "verbose_name_plural": "Параметры товаров",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Заказанное количество", verbose_name="Количество"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена за единицу товара на момент оформления",
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Заказ, в который входит данная позиция",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_items",
                        to="shop_app.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Ссылка на карточку товара",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop_app.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        help_text="Поставщик данного товара в момент заказа",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop_app.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="shop",
            field=models.ForeignKey(
                help_text="Магазин, к которому относится данная категория",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="shop_app.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("original_id", "category"), name="unique_product_per_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="productparameter",
            constraint=models.UniqueConstraint(
                fields=("product", "parameter"), name="unique_parameter_for_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("original_id", "shop"), name="unique_category_per_shop"
            ),
        ),
    ]
