# Generated by Django 6.0.6 on 2026-06-12 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название магазина(поставщика)', max_length=100, unique=True, verbose_name='Название')),
                ('url', models.URLField(blank=True, help_text='URL поставщика', null=True, verbose_name='Ссылка')),
                ('state', models.BooleanField(db_index=True, default=True, help_text='Включено - магазин принимает заказы, Выключено - импорт идет, но заказы не принимаются', verbose_name='Статус приёма заказов')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.PositiveIntegerField(help_text='ID категории из прайс-листа поставщика', primary_key=True, serialize=False, verbose_name='ID категории')),
                ('name', models.CharField(help_text='Название категории (например: Смартфоны)', max_length=100, verbose_name='Название')),
                ('shop', models.ForeignKey(help_text='Магазин, к которому относится данная категория', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop_app.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Уникальный идентификатор товара из системы поставщика', primary_key=True, serialize=False, verbose_name='ID товара')),
                ('name', models.CharField(help_text='Полное название товара', max_length=255, verbose_name='Название')),
                ('model', models.CharField(blank=True, help_text='Техническое название модели (например: apple/iphone/xs-max)', max_length=255, verbose_name='Модель')),
                ('price', models.DecimalField(decimal_places=2, help_text='Текущая цена закупки', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('price_rrc', models.DecimalField(decimal_places=2, help_text='Рекомендуемая розничная цена (РРЦ)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рекомендуемая розничная цена')),
                ('quantity', models.PositiveIntegerField(help_text='Текущий остаток на складе поставщика', verbose_name='Количество на складе')),
                ('category', models.ForeignKey(help_text='Категория, к которой принадлежит товар', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'constraints': [models.UniqueConstraint(fields=('id', 'category'), name='unique_product_per_category')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('id', 'shop'), name='unique_category_per_shop'),
        ),
    ]
