# Generated by Django 6.0.6 on 2026-06-12 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название свойства товара (например: "Диагональ (дюйм)")', max_length=100, unique=True, verbose_name='Название характеристики')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='Уникальное название магазина (поставщика)', max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Значение характеристики (например: "6.5" или "золотистый")', max_length=255, verbose_name='Значение')),
                ('parameter', models.ForeignKey(help_text='Наименование характеристики из справочника', on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='shop_app.parameter', verbose_name='Параметр')),
                ('product', models.ForeignKey(help_text='Товар, к которому привязана характеристика', on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='shop_app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Параметр товара',
                'verbose_name_plural': 'Параметры товаров',
                'constraints': [models.UniqueConstraint(fields=('product', 'parameter'), name='unique_parameter_for_product')],
            },
        ),
    ]
