# Generated by Django 6.0.6 on 2026-06-13 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_parameter_alter_shop_name_productparameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Город доставки', max_length=50, verbose_name='Город')),
                ('street', models.CharField(help_text='Улица доставки', max_length=100, verbose_name='Улица')),
                ('house', models.CharField(blank=True, help_text='Номер дома', max_length=15, verbose_name='Дом')),
                ('structure', models.CharField(blank=True, help_text='Номер корпуса', max_length=15, verbose_name='Корпус')),
                ('building', models.CharField(blank=True, help_text='Номер строения', max_length=15, verbose_name='Строение')),
                ('apartment', models.CharField(blank=True, help_text='Номер квартиры', max_length=15, verbose_name='Квартира')),
                ('phone', models.CharField(help_text='Контактный номер телефона', max_length=20, verbose_name='Телефон')),
                ('user', models.ForeignKey(help_text='Владелец адреса доставки', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('state', models.CharField(choices=[('basket', 'Статус корзины'), ('new', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], db_index=True, default='basket', help_text='Текущий статус заказа', max_length=15, verbose_name='Статус')),
                ('contact', models.ForeignKey(blank=True, help_text='Адрес доставки (заполняется при подтверждении заказа из корзины)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.contact', verbose_name='Контакт')),
                ('user', models.ForeignKey(help_text='Покупатель, оформивший заказ', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-dt',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Заказанное количество', verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за единицу товара на момент оформления', max_digits=10, verbose_name='Цена')),
                ('order', models.ForeignKey(help_text='Заказ, в который входит данная позиция', on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='shop_app.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(help_text='Ссылка на карточку товара', on_delete=django.db.models.deletion.PROTECT, to='shop_app.product', verbose_name='Продукт')),
                ('shop', models.ForeignKey(help_text='Поставщик данного товара в момент заказа', on_delete=django.db.models.deletion.PROTECT, to='shop_app.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
