name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 60066
          script: |
            cd ~/Diplom_Shop
            git fetch origin
            git reset --hard origin/main
            docker-compose down
            docker-compose up -d --build

            echo "Ожидание 10 секунд пока поднимутся все контейнеры..."
            sleep 10

            echo "Проверка статуса контейнеров..."

            if docker-compose ps | grep -q "Exit"; then
              echo "ОШИБКА: Контейнер упал при запуске! Логи:"
              docker-compose logs web
              exit 1
            fi

            echo "Деплой ОК!"
